package main

import "os"
import "fmt"
import "mapreduce"
import "unicode"
import "strings"
import "container/list"
import "strconv"

const Debug = 0

func DPrintf(format string, a ...interface{}) (n int, err error) {
	if Debug > 0 {
		n, err = fmt.Printf(format, a...)
	}
	return
}

// our simplified version of MapReduce does not supply a
// key to the Map function, as in the paper; only a value,
// which is a part of the input file content. the return
// value should be a list of key/value pairs, each represented
// by a mapreduce.KeyValue.
func Map(value string) *list.List {
	//DPrintf("Map %v\n", value)
	mapList := list.New()
	f := func(c rune) bool {
		return !unicode.IsLetter(c) && !unicode.IsNumber(c)
	}
	mapWords := strings.FieldsFunc(value, f)
	//mapWords = strings.Fields(value)
	for _, w := range mapWords{
		//DPrintf("Map %v\n", w)
		kv := mapreduce.KeyValue{w, "1"}
		DPrintf("test %s %s\n", kv.Key, kv.Value)
		mapList.PushBack(kv)
	}
	return mapList
}

// called once for each key generated by Map, with a list
// of that key's string value. should return a single
// output value for that key.
func Reduce(key string, values *list.List) string {
	//count := 0
	//for w := values.Front(); w != nil; w = w.Next() {
		//kv := w.Value//.(mapreduce.KeyValue)
		//DPrintf("Reduce %s %s\n", key, kv)
		//if key == w.Value {
	//		count++
		//}
	//}
	//return strconv.Itoa(count)
	return strconv.Itoa(values.Len())
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master x.txt sequential)
// 2) Master (e.g., go run wc.go master x.txt localhost:7777)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) != 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		if os.Args[3] == "sequential" {
			mapreduce.RunSingle(5, 3, os.Args[2], Map, Reduce)
		} else {
			mr := mapreduce.MakeMapReduce(5, 3, os.Args[2], os.Args[3])
			// Wait until MR is done
			<-mr.DoneChannel
		}
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], Map, Reduce, 100)
	}
}
